baseURL = "https://howinator.io/"
languageCode = "en-us"
title = "howinator howinatin"
theme = "timberline"
sectionPagesMenu = true
enableEmoji = true

[params]
    author = "Howie Benefiel"
    description = "Howie's thoughts on things"
    avatar = "headshot-v2.jpg"
    tagline = "Builder. People & Product."

[permalinks]
    blog = "/:year/:month/:day/:slug"

[params.social]
    Github = "howinator"
    Twitter = "howiesxsw"
    Email = "blog@howinator.io"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
  [markup.highlight]
    noClasses = false
    guessSyntax = true

[menu]
  [[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
  [[menu.main]]
    name = "claude log"
    identifier = "claude-log"
    weight = 200
    url = "/claude-log/"
  [[menu.main]]
    name = "resume"
    identifier = "resume"
    weight = 300
    url = "/resume.pdf"
